spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/01blog
    username: postgres
    password: "00000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB

blog:
  app:
    jwtSecret: "MDFibG9nLWFwcGxpY2F0aW9uLXNlY3JldC1rZXktZm9yLWp3dC1hdXRoZW50aWNhdGlvbg=="
    jwtExpirationMs: 86400000

file:
  upload-dir: ./uploads